// Copyright 2025, 2026 The HuaTuo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package tracing

import (
	"context"
	"crypto/rand"
	"errors"
	"fmt"
	"math/big"
	"os/exec"
	"path"
	"path/filepath"
	"sort"
	"sync"
	"time"
)

// Status represents the status of a task.
type Status string

const (
	// StatusCompleted represents a task that has finished executing successfully.
	StatusCompleted = "completed"
	// StatusFailed represents a task that encountered an error during execution.
	StatusFailed = "failed"
	// StatusPending represents a task that has been created but has not yet begun execution.
	StatusPending = "pending"
	// StatusRunning represents a task that is currently being executed.
	StatusRunning = "running"
	// StatusNotExist represents a task that has either never been created or has been removed.
	StatusNotExist = "not_exist"
)

var TaskBinDir = "bin"

type TaskStorageType int

const (
	TaskStorageDB TaskStorageType = iota + 1
	TaskStorageStdout
	TaskStorageLocal
	TaskStorageDBJSON // JSON data
)

type TaskResult struct {
	TaskStatus Status
	TaskData   []byte
	TaskErr    error
}

// TaskInfo is a lightweight task summary returned by list APIs.
type TaskInfo struct {
	TaskID     string `json:"task_id"`
	TracerName string `json:"tracer_name"`
	Status     Status `json:"status"`
}

// task represents a unit of work to be executed.
type task struct {
	mu           sync.Mutex
	id           string             // Unique identifier for the task.
	execBinary   string             // Path to the executable file to run for this task.
	execArgs     []string           // Arguments to pass to the executable.
	stdoutData   []byte             // Data generated by the task.
	status       Status             // Current status of the task.
	error        error              // Error encountered during task execution.
	storage      TaskStorageType    // Type of data produced by the task.
	cancelFunc   context.CancelFunc // Function to cancel the task.
	doneCh       chan struct{}
	deadlineTime time.Time // Time after which the task will be automatically deleted.
}

var (
	taskLifeTmpCache sync.Map
	taskCreateMu     sync.Mutex
	// ErrTaskNotFound Error returned when a task is not found.
	ErrTaskNotFound = errors.New("task not found")
	// ErrTaskTimeout Error returned when a task times out.
	ErrTaskTimeout = errors.New("task timeout")
	// ErrTaskCanceled Error returned when a task is canceled.
	ErrTaskCanceled = errors.New("task canceled")
	// ErrTaskLimitExceeded is returned when a new task would exceed the active limit.
	ErrTaskLimitExceeded = errors.New("too many running tasks")
)

func init() {
	go tasksGarbageCollect()
}

func tasksGarbageCollect() {
	ticker := time.NewTicker(time.Second * 10)
	defer ticker.Stop()

	for range ticker.C {
		now := time.Now()
		taskLifeTmpCache.Range(func(key, value any) bool {
			task, ok := value.(*task)
			if !ok {
				taskLifeTmpCache.Delete(key)
				return true
			}

			task.mu.Lock()
			expired := (task.status == StatusCompleted || task.status == StatusFailed) &&
				now.After(task.deadlineTime)
			task.mu.Unlock()
			if expired {
				taskLifeTmpCache.Delete(key)
			}
			return true
		})
	}
}

// AllocTaskID returns a fresh random identifier suitable for tasks and tracer
// records.
func AllocTaskID() (string, error) {
	const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
	const length = 16
	result := make([]byte, length)
	charsetLength := big.NewInt(int64(len(charset)))

	for i := range result {
		num, err := rand.Int(rand.Reader, charsetLength)
		if err != nil {
			return "", fmt.Errorf("generate random task id: %w", err)
		}
		result[i] = charset[num.Int64()]
	}

	return string(result), nil
}

// NewTask creates a new task, allocates an ID, and starts it.
func NewTask(execBinary string, timeout time.Duration, storageType TaskStorageType, execArgs []string) string {
	taskID, err := AllocTaskID()
	if err != nil {
		return ""
	}
	if _, err := NewTaskWithID(taskID, execBinary, timeout, storageType, execArgs); err != nil {
		return ""
	}
	return taskID
}

// NewTaskWithID creates a task with an idempotency key supplied by the caller.
func NewTaskWithID(
	taskID string,
	execBinary string,
	timeout time.Duration,
	storageType TaskStorageType,
	execArgs []string,
) (string, error) {
	return NewTaskWithIDLimit(taskID, execBinary, timeout, storageType, execArgs, 0)
}

// NewTaskWithIDLimit creates an idempotent task while enforcing an active limit.
func NewTaskWithIDLimit(
	taskID string,
	execBinary string,
	timeout time.Duration,
	storageType TaskStorageType,
	execArgs []string,
	maxActive int,
) (string, error) {
	if taskID == "" {
		return "", errors.New("task id is required")
	}
	if err := validateTaskBinary(execBinary); err != nil {
		return "", err
	}
	taskCreateMu.Lock()
	defer taskCreateMu.Unlock()
	if _, loaded := taskLifeTmpCache.Load(taskID); loaded {
		return taskID, nil
	}
	if maxActive > 0 && activeTaskCount() >= maxActive {
		return "", ErrTaskLimitExceeded
	}
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	task := &task{
		id:         taskID,
		status:     StatusPending,
		cancelFunc: cancel,
		execBinary: execBinary,
		storage:    storageType,
		execArgs:   append([]string(nil), execArgs...),
		doneCh:     make(chan struct{}),
	}
	taskLifeTmpCache.Store(taskID, task)

	go runTask(ctx, task)

	return taskID, nil
}

func activeTaskCount() int {
	count := 0
	taskLifeTmpCache.Range(func(_, value any) bool {
		task, ok := value.(*task)
		if !ok {
			return true
		}
		task.mu.Lock()
		active := task.status == StatusPending || task.status == StatusRunning
		task.mu.Unlock()
		if active {
			count++
		}
		return true
	})
	return count
}

// validateTaskBinary restricts the tracer name to a bare file name resolved
// inside TaskBinDir. The task API is reachable without authentication, so a
// caller-supplied name such as "../bin/bash" or "/bin/sh" must never reach
// exec.CommandContext.
func validateTaskBinary(execBinary string) error {
	if execBinary == "" || execBinary == "." || execBinary == ".." ||
		filepath.Base(execBinary) != execBinary {
		return fmt.Errorf("task binary %q must be a bare file name within the tool directory", execBinary)
	}
	return nil
}

func runTask(ctx context.Context, task *task) {
	defer close(task.doneCh)
	defer task.cancelFunc()

	task.mu.Lock()
	task.status = StatusRunning
	task.mu.Unlock()

	cmd := exec.CommandContext(ctx, path.Join(TaskBinDir, task.execBinary), task.execArgs...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		contextErr := ctx.Err()
		var taskErr error
		if errors.Is(contextErr, context.DeadlineExceeded) {
			taskErr = ErrTaskTimeout
		} else if errors.Is(contextErr, context.Canceled) {
			taskErr = ErrTaskCanceled
		} else {
			taskErr = fmt.Errorf("task error: %s| cmd error: %s", err.Error(), string(output))
		}

		task.mu.Lock()
		task.status = StatusFailed
		task.error = taskErr
		task.deadlineTime = time.Now().Add(10 * time.Minute)
		task.mu.Unlock()
		return
	}

	saveTaskOutputByType(task, time.Now(), output)

	task.mu.Lock()
	task.status = StatusCompleted
	task.deadlineTime = time.Now().Add(10 * time.Minute)
	task.mu.Unlock()
}

func saveTaskOutputByType(task *task, startAt time.Time, output []byte) {
	switch task.storage {
	case TaskStorageDB:
		_ = SaveTaskOutputText(&WriteRequest{
			TracerName: task.execBinary,
			TracerID:   task.id,
			TracerTime: startAt,
			TracerData: string(output),
		})
	case TaskStorageDBJSON:
		_ = SaveTaskOutputJSON(&WriteRequest{
			TracerName: task.execBinary,
			TracerID:   task.id,
			TracerTime: startAt,
			TracerData: string(output),
		})
	case TaskStorageStdout:
		task.mu.Lock()
		task.stdoutData = append(task.stdoutData, output...)
		task.mu.Unlock()
	case TaskStorageLocal:
	default:
	}
}

func setDeadlineDefault(task *task) {
	task.mu.Lock()
	defer task.mu.Unlock()

	task.deadlineTime = time.Now().Add(10 * time.Minute)
}

// RunningTaskCount gets the number of running tasks.
func RunningTaskCount() int {
	count := 0
	taskLifeTmpCache.Range(func(key, value any) bool {
		task, ok := value.(*task)
		if !ok {
			return true
		}

		task.mu.Lock()
		if task.status == StatusRunning {
			count++
		}
		task.mu.Unlock()
		return true
	})
	return count
}

// ListTasks returns summaries for all tasks currently kept in memory.
func ListTasks() []TaskInfo {
	tasks := make([]TaskInfo, 0)
	taskLifeTmpCache.Range(func(key, value any) bool {
		task, ok := value.(*task)
		if !ok {
			return true
		}

		task.mu.Lock()
		taskID := task.id
		if taskID == "" {
			if keyID, ok := key.(string); ok {
				taskID = keyID
			}
		}
		tasks = append(tasks, TaskInfo{
			TaskID:     taskID,
			TracerName: task.execBinary,
			Status:     task.status,
		})
		task.mu.Unlock()
		return true
	})

	sort.Slice(tasks, func(i, j int) bool {
		return tasks[i].TaskID < tasks[j].TaskID
	})
	return tasks
}

// Result returns the result of a task given its ID.
func Result(taskID string) *TaskResult {
	taskInterface, ok := taskLifeTmpCache.Load(taskID)
	if !ok {
		return &TaskResult{
			TaskStatus: StatusNotExist,
			TaskErr:    ErrTaskNotFound,
		}
	}

	task, ok := taskInterface.(*task)
	if !ok {
		return &TaskResult{
			TaskStatus: StatusNotExist,
			TaskErr:    fmt.Errorf("invalid task type for id %s", taskID),
		}
	}

	task.mu.Lock()
	defer task.mu.Unlock()
	if task.status == StatusFailed || task.status == StatusCompleted {
		task.deadlineTime = time.Now().Add(10 * time.Minute)
	}
	return &TaskResult{
		TaskData:   append([]byte(nil), task.stdoutData...),
		TaskStatus: task.status,
		TaskErr:    task.error,
	}
}

// StopTask stops a running task given its ID.
func StopTask(taskID string) error {
	taskAny, ok := taskLifeTmpCache.Load(taskID)
	if !ok {
		return ErrTaskNotFound
	}

	task, ok := taskAny.(*task)
	if !ok {
		return fmt.Errorf("invalid task type for id %s", taskID)
	}

	task.mu.Lock()
	status := task.status
	cancel := task.cancelFunc
	doneCh := task.doneCh
	task.mu.Unlock()
	if cancel != nil && (status == StatusPending || status == StatusRunning) {
		cancel()
	}
	if doneCh != nil {
		<-doneCh
	}
	taskLifeTmpCache.Delete(taskID)
	return nil
}
